Repository lucky-treee/poom-fe, pull requests merged in 2023-02, with the labels that each got.

#45 [#16] semantic-release를 통해 버저닝을 할 수 있다.
  .github/workflows/beta-merge.yml
  .github/workflows/develop.yml
  .github/workflows/main-merge.yml
  .releaserc
  package.json
  yarn.lock
Labels: 🚃 프로젝트

#46 [#44] dependabot alert를 해결한다.
  .storybook/main.cjs
  package.json
  yarn.lock
Labels: 🐛 버그

#47 0.1.0 배포
  .env.sample
  .eslintrc.cjs
  .github/pull_request_template.md
  .github/workflows/beta-merge.yml
  .github/workflows/develop.yml
  .github/workflows/main-merge.yml
  .gitignore
  .releaserc
  .storybook/main.cjs
  .storybook/preview-head.html
  .storybook/preview.cjs
  README.md
  index.html
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/assets/AddShopIcon.svg
  src/assets/Locate.svg
  src/assets/MapIcon.tsx
  src/assets/NavigatorCurve.tsx
  src/assets/ProfileIcon.tsx
  src/assets/user.svg
  src/components/Link.tsx
  src/components/Navigator.tsx
  src/components/Typography.tsx
  src/components/map/LocateButton.tsx
  src/components/map/UserMarker.tsx
  src/constants/PathName.ts
  src/index.css
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
  src/models/Location.ts
  src/pages/LoginPage.tsx
  src/pages/MapPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ShopPage.tsx
  src/pages/SignUpPage.tsx
  src/stories/BorderRadius.stories.tsx
  src/stories/Color.stories.tsx
  src/stories/LocateButton.stories.tsx
  src/stories/Map.stories.tsx
  src/stories/Shadow.stories.tsx
  src/stories/Typography.stories.tsx
  src/utils/i18n/index.ts
  src/utils/i18n/locales/ko_KR/translation.json
  src/vite-env.d.ts
  tailwind.config.cjs
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 🚃 프로젝트

#48 [#31] MSW를 사용한 모킹에서 asset을 불러올 때 콘솔 오류를 해결한다.
  src/main.tsx
Labels: 🧪 테스트

#52 [#34] ErrorBoundary를 추가해서 에러 화면을 보여준다.
  .eslintrc.cjs
  index.html
  src/App.tsx
  src/ErrorBoundary.tsx
  src/components/Typography.tsx
  src/index.css
  src/main.tsx
  src/pages/error/NotFoundErrorPage.tsx
  src/pages/error/UnknownErrorPage.tsx
  src/stories/BorderRadius.stories.tsx
  src/stories/Color.stories.tsx
  src/stories/LocateButton.stories.tsx
  src/stories/Map.stories.tsx
  src/stories/Shadow.stories.tsx
  src/stories/Typography.stories.tsx
  src/utils/i18n/locales/ko_KR/translation.json
  tailwind.config.cjs
Labels: ⛳️ 기능

#51 [#14] 프로젝트에서 Input, Select, Button을 사용할 수 있다.
  public/mockServiceWorker.js
  src/components/Button.tsx
  src/components/InputBox.tsx
  src/stories/Button.stories.tsx
  src/stories/InputBox.stories.tsx
  tailwind.config.cjs
Labels: 📖 문서화, ⛳️ 기능

#59 [#58] Vite Proxy를 수정하여 로컬에서도 API를 요청할 수 있다.
  .env.sample
  .eslintrc.cjs
  .nvmrc
  src/App.tsx
  src/api/shop.ts
  src/assets/components/navigate/AddShopIcon.svg
  src/assets/components/navigate/MapIcon.tsx
  src/assets/components/navigate/NavigatorCurve.tsx
  src/assets/components/navigate/ProfileIcon.tsx
  src/assets/components/navigate/user.svg
  src/assets/map/Locate.svg
  src/components/Navigator.tsx
  src/components/map/LocateButton.tsx
  src/components/map/UserMarker.tsx
  src/config/index.ts
  src/hooks/api/useFetchShopList.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/server.ts
  src/models/shop/Shop.ts
  src/models/shop/response.ts
  src/pages/MapPage.tsx
  src/pages/error/NotFoundErrorPage.tsx
  src/pages/error/UnknownErrorPage.tsx
  src/service/index.ts
  src/service/shop.ts
  src/stories/LocateButton.stories.tsx
  vite.config.ts
Labels: 🐛 버그, ⛳️ 기능, 🔧 리펙토링
