Repository lucky-treee/poom-fe, pull requests merged in 2023-04, with the labels that each got.

#87 [#70] 가게 미리보기를 위로 올려 가게 상세보기를 볼 수 있다.
  src/assets/components/Heart.svg
  src/components/LocalDate.tsx
  src/components/shop/Shop.tsx
  src/hooks/api/useFetchShopReviewList.ts
  src/hooks/api/useGetShopById.ts
  src/mocks/handlers.ts
  src/models/auth/Review.ts
  src/models/shop/Shop.ts
  src/models/shop/response.ts
  src/pages/ShopPage.tsx
  src/service/shop.ts
  src/utils/i18n/locales/ko_KR/translation.json
Labels: ⛳️ 기능

#90 [#89] model/auth 폴더에 있는 review model을 적절한 위치로 이동시킨다.
  src/components/auth/SignUpForm.tsx
  src/hooks/api/useFetchBookmarkList.ts
  src/hooks/api/useFetchShopReviewList.ts
  src/hooks/api/useFetchUserReviewList.ts
  src/models/bookmark/index.ts
  src/models/review/index.ts
  src/models/shop/response.ts
  src/pages/ShopPage.tsx
Labels: 🔧 리펙토링

#93 [#80] Select 컴포넌트의 Option 가독성을 높인다.
  src/components/HashtagChip.tsx
  src/components/LocalDate.tsx
  src/components/MapInput.tsx
  src/components/Navigator.tsx
  src/components/ReviewContent.tsx
  src/components/ReviewImageList.tsx
  src/components/ReviewTitleHeader.tsx
  src/components/ShopDrawer.tsx
  src/components/ShopRegisterForm.tsx
  src/components/auth/NicknameInput.tsx
  src/components/auth/ProfileSelectModal.tsx
  src/components/auth/SignUpForm.tsx
  src/components/base/Button.tsx
  src/components/base/Input.tsx
  src/components/base/Link.tsx
  src/components/base/Modal.tsx
  src/components/base/Select.tsx
  src/components/base/Typography.tsx
  src/components/profile/BookmarkPreview.tsx
  src/components/profile/LoginAlertProfile.tsx
  src/components/profile/Profile.tsx
  src/components/profile/SectionButton.tsx
  src/components/shop/Shop.tsx
  src/pages/AuthPage.tsx
  src/pages/BookmarkManagePage.tsx
  src/pages/LoginPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ReviewManagePage.tsx
  src/pages/ShopPage.tsx
  src/pages/ShopRegisterPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/SignUpSuccessPage.tsx
  src/pages/error/NotFoundErrorPage.tsx
  src/pages/error/UnknownErrorPage.tsx
  src/pages/error/auth/LoginFailErrorPage.tsx
  src/pages/error/auth/NoKakaoCodeErrorPage.tsx
  src/pages/error/auth/NotMemberErrorPage.tsx
  src/stories/Button.stories.tsx
  src/stories/Input.stories.tsx
  src/stories/Select.stories.tsx
  src/stories/Typography.stories.tsx
  tailwind.config.cjs
Labels: 🔧 리펙토링

#94 [#82] API 성공 실패에 대한 피드백을 제공한다.
  src/App.tsx
  src/assets/components/toast/close.svg
  src/assets/components/toast/error.svg
  src/assets/components/toast/info.svg
  src/assets/components/toast/success.svg
  src/assets/components/toast/warn.svg
  src/components/base/Toast.tsx
  src/components/base/ToastProvider.tsx
  src/hooks/api/useLogin.ts
  src/hooks/useToast.ts
  src/models/ToastContext.ts
  src/pages/ProfilePage.tsx
  src/utils/i18n/locales/ko_KR/translation.json
Labels: ⛳️ 기능

#92 [#91] 하단바의 문제점을 수정한다.
  src/assets/components/navigate/NavigatorCurve.svg
  src/assets/components/navigate/NavigatorCurve.tsx
  src/components/Navigator.tsx
Labels: 🔧 리펙토링

#108 [#107] 가게 등록 페이지의 버그와 스타일이 맞지 않는 것을 수정한다.
  src/assets/components/SmallLoading.svg
  src/components/LoadingProgressIcon.tsx
  src/components/Navigator.tsx
  src/components/ShopRegisterForm.tsx
  src/components/base/Button.tsx
  src/pages/ShopRegisterPage.tsx
Labels: 🐛 버그

#105 [#88] 사용자는 Access Token이 만료된 경우 Access Token을 자동으로 발급 받을 수 있다.
  .eslintrc.cjs
  src/hooks/api/useFetchShopList.ts
  src/hooks/api/useGetShopById.ts
  src/hooks/api/useKakaoLogin.ts
  src/hooks/api/useLogin.ts
  src/hooks/api/useRefreshAccessToken.ts
  src/hooks/useAccessToken.ts
  src/models/auth/response.ts
  src/pages/MapPage.tsx
  src/pages/ProfilePage.tsx
  src/service/auth.ts
  src/service/index.ts
  src/service/shop.ts
  src/utils/SessionStorage.ts
Labels: ⛳️ 기능, 🔧 리펙토링
