Repository lucky-treee/poom-fe, pull requests merged in 2023-03, with the labels that each got.

#57 [#50] 사용자는 카카오 API를 사용해 로그인 할 수 있다.
  src/App.tsx
  src/assets/app/poom.svg
  src/assets/auth/kakaoLoginMedium.png
  src/assets/components/Loading.svg
  src/components/LoadingProgressIcon.tsx
  src/config/index.ts
  src/constants/KakaoPath.ts
  src/constants/PathName.ts
  src/constants/Terms.ts
  src/hooks/api/useLogin.ts
  src/hooks/useKakaoLogin.ts
  src/mocks/handlers.ts
  src/models/auth/LoginFrom.ts
  src/models/auth/response.ts
  src/pages/AuthPage.tsx
  src/pages/LoginPage.tsx
  src/service/auth.ts
  src/service/index.ts
  src/utils/i18n/locales/ko_KR/translation.json
  vite.config.ts
Labels: ⛳️ 기능

#60 [#32] 사용자는 내 정보 화면을 확인할 수 있다.
  .eslintrc.cjs
  src/assets/auth/arrow-forward.svg
  src/assets/auth/mingcute_pencil-fill.svg
  src/components/Typography.tsx
  src/components/profile/LoginAlertProfile.tsx
  src/components/profile/Profile.tsx
  src/components/profile/SectionButton.tsx
  src/constants/PathName.ts
  src/hooks/api/useGetUserInformation.ts
  src/mocks/handlers.ts
  src/models/auth/Profile.ts
  src/models/auth/response.ts
  src/pages/ProfilePage.tsx
  src/service/auth.ts
  src/utils/i18n/locales/ko_KR/translation.json
Labels: ⛳️ 기능

#62 [#61] Input과 Button 컴포넌트를 고도화한다.
  package.json
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/InputBox.tsx
  src/service/auth.ts
  src/stories/Button.stories.tsx
  src/stories/Input.stories.tsx
  src/stories/InputBox.stories.tsx
  yarn.lock
Labels: 🔧 리펙토링

#63 [#39] 사용자는 회원가입 할 수 있다.
  .eslintrc.cjs
  index.html
  src/App.tsx
  src/assets/components/navigate/back.svg
  src/components/Modal.tsx
  src/components/auth/NicknameInput.tsx
  src/components/auth/ProfileImagePreview.tsx
  src/components/auth/ProfileSelectModal.tsx
  src/components/auth/SignUpForm.tsx
  src/constants/PathName.ts
  src/hooks/api/useSignUp.ts
  src/mocks/handlers.ts
  src/models/auth/SignUpForm.ts
  src/models/auth/request.ts
  src/pages/AuthPage.tsx
  src/pages/LoginPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/SignUpSuccessPage.tsx
  src/service/auth.ts
  src/utils/i18n/locales/ko_KR/translation.json
Labels: ⛳️ 기능

#75 [#11] 지도에 가게 정보를 표시할 수 있다.
  src/assets/components/navigate/shop.svg
  src/components/ Drawer.tsx
  src/components/ShopModal.tsx
  src/components/map/ShopMarker.tsx
  src/pages/MapPage.tsx
  src/stories/Drawer.stories.tsx
Labels: ⛳️ 기능

#78 [#67] 사용자는 가게를 등록할 수 있다.
  package.json
  src/App.tsx
  src/assets/components/DropDown.svg
  src/assets/components/DropUp.svg
  src/assets/components/Dropdown.svg
  src/assets/components/Loading.svg
  src/assets/map/SmallLocate.svg
  src/components/Button.tsx
  src/components/HashtagChip.tsx
  src/components/Input.tsx
  src/components/LoadingProgressIcon.tsx
  src/components/MapInput.tsx
  src/components/Navigator.tsx
  src/components/Select.tsx
  src/components/ShopDrawer.tsx
  src/components/ShopRegisterForm.tsx
  src/components/map/ShopMarker.tsx
  src/constants/PathName.ts
  src/hooks/api/useRegisterShop.ts
  src/hooks/useThrottledState.ts
  src/main.tsx
  src/models/Shop.ts
  src/models/response.ts
  src/models/shop/ShopRegisterForm.ts
  src/models/shop/request.ts
  src/pages/AuthPage.tsx
  src/pages/MapPage.tsx
  src/pages/ShopRegisterPage.tsx
  src/service/shop.ts
  src/stories/Drawer.stories.tsx
  src/stories/HashtagChip.stories.tsx
  src/utils/i18n/locales/ko_KR/translation.json
Labels: ⛳️ 기능, 🔧 리펙토링

#83 [#77] 카카오 로그인 버튼을 통해 실제로 로그인이 가능하다.
  README.md
  package.json
  public/mockServiceWorker.js
  src/assets/components/Check.svg
  src/components/auth/ProfileImagePreview.tsx
  src/components/auth/ProfileSelectModal.tsx
  src/components/auth/SignUpForm.tsx
  src/components/profile/LoginAlertProfile.tsx
  src/config/index.ts
  src/constants/KakaoPath.ts
  src/constants/ProfileImageList.ts
  src/hooks/api/useGetUserInformation.ts
  src/hooks/api/useKakaoLogin.ts
  src/hooks/api/useLogin.ts
  src/hooks/api/useSignUp.ts
  src/hooks/useAccessToken.ts
  src/hooks/useKakaoLogin.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useQueryKakaoLogin.ts
  src/hooks/useRedirectPath.ts
  src/mocks/handlers.ts
  src/models/auth/LoginFrom.ts
  src/models/auth/SignUpForm.ts
  src/models/auth/request.ts
  src/models/auth/response.ts
  src/pages/AuthPage.tsx
  src/pages/LoginPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/SignUpPage.tsx
  src/pages/error/auth/LoginFailErrorPage.tsx
  src/pages/error/auth/NoKakaoCodeErrorPage.tsx
  src/pages/error/auth/NotMemberErrorPage.tsx
  src/service/auth.ts
  src/service/index.ts
  src/utils/i18n/locales/ko_KR/translation.json
  vite.config.ts
  yarn.lock
Labels: ⛳️ 기능

#84 [#28] CI 과정에서 불필요하게 Dependency를 여러번 받는 과정을 간소화한다.
  .github/workflows/beta-merge.yml
  .github/workflows/develop.yml
  .github/workflows/main-merge.yml
Labels: 🚃 프로젝트

#85 [#37] 사용자는 내 정보화면에서 즐겨찾기 한 가게를 볼 수 있다.
  src/App.tsx
  src/assets/components/Favorite.svg
  src/assets/components/NoImage.svg
  src/assets/components/navigate/Back.svg
  src/assets/components/navigate/back.svg
  src/components/HashtagChip.tsx
  src/components/MapInput.tsx
  src/components/Typography.tsx
  src/components/profile/BookmarkPreview.tsx
  src/components/profile/SectionButton.tsx
  src/constants/PathName.ts
  src/hooks/api/useFetchBookmarkList.ts
  src/mocks/handlers.ts
  src/models/auth/Bookmark.ts
  src/models/auth/response.ts
  src/pages/BookmarkManagePage.tsx
  src/pages/LoginPage.tsx
  src/pages/ProfilePage.tsx
  src/pages/ShopRegisterPage.tsx
  src/pages/SignUpPage.tsx
  src/service/auth.ts
  src/utils/i18n/locales/ko_KR/translation.json
Labels: ⛳️ 기능

#86 [#73] 사용자는 프로필 페이지 > 리뷰 관리 페이지에서 리뷰를 확인하고 수정 / 삭제 할 수 있다.
  src/App.tsx
  src/assets/components/ActionMenu.svg
  src/assets/components/Camera.svg
  src/components/ActionMenu.tsx
  src/components/Button.tsx
  src/components/LocalDate.tsx
  src/components/ReviewContent.tsx
  src/components/ReviewImageList.tsx
  src/components/ReviewTitleHeader.tsx
  src/hooks/api/useFetchUserReviewList.ts
  src/mocks/handlers.ts
  src/models/auth/Review.ts
  src/models/auth/response.ts
  src/pages/ReviewManagePage.tsx
  src/service/auth.ts
  src/utils/i18n/locales/ko_KR/translation.json
Labels: ⛳️ 기능
