Repository lucky-treee/poom-fe, pull requests merged in 2023-01, with the labels that each got.

#7 [#4] ci 파일을 추가하여 lint가 실패한 경우 배포하지 못하게 한다.
  .github/workflows/beta-merge.yml
  .github/workflows/develop.yml
  .github/workflows/main-merge.yml
Labels: 🚃 프로젝트

#17 [#13] 사용할 디자인 시스템을 코드로 옮기고, storybook을 사용해 확인할 수 있다.
  .eslintrc.cjs
  .storybook/main.cjs
  .storybook/preview-head.html
  .storybook/preview.cjs
  index.html
  package.json
  src/components/Link.tsx
  src/components/Typography.tsx
  src/index.css
  src/stories/BorderRadius.stories.tsx
  src/stories/Color.stories.tsx
  src/stories/Shadow.stories.tsx
  src/stories/Typography.stories.tsx
  tailwind.config.cjs
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: 📖 문서화, ⛳️ 기능, 🧪 테스트

#20 [#8] 지도 API를 사용하여 사용자 주변 지도를 출력할 수 있다.
  .env.sample
  .github/pull_request_template.md
  .github/workflows/beta-merge.yml
  .github/workflows/develop.yml
  .github/workflows/main-merge.yml
  .gitignore
  .storybook/preview-head.html
  README.md
  index.html
  package.json
  src/App.tsx
  src/constants/PathName.ts
  src/pages/MapPage.tsx
  src/stories/Map.stories.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ⛳️ 기능

#26 [#18] Mocking을 통해 서버 데이터가 준비되지 않았더라도 서버로부터 응답을 받을 수 있다.
  .env.sample
  .github/workflows/develop.yml
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
  tsconfig.json
  yarn.lock
Labels: 🧪 테스트

#29 [#9] 사용자는 지도에서 자신의 위치를 알 수 있다.
  .eslintrc.cjs
  .storybook/main.cjs
  package.json
  src/assets/Locate.svg
  src/assets/user.svg
  src/components/map/LocateButton.tsx
  src/components/map/UserMarker.tsx
  src/index.css
  src/models/Location.ts
  src/pages/MapPage.tsx
  src/stories/LocateButton.stories.tsx
  src/vite-env.d.ts
  tailwind.config.cjs
  vite.config.ts
  yarn.lock
Labels: ⛳️ 기능

#30 [#21] 네비게이션을 통해 페이지를 이동할 수 있다.
  src/assets/AddShopIcon.svg
  src/assets/MapIcon.tsx
  src/assets/NavigatorCurve.tsx
  src/assets/ProfileIcon.tsx
  src/components/Navigator.tsx
  src/pages/MapPage.tsx
  src/pages/ProfilePage.tsx
  src/utils/i18n/locales/ko_KR/translation.json
  tailwind.config.cjs
Labels: ⛳️ 기능
